### ISSUE TITLE
escaped whitespace in fstab not honored

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#122]
The fstab abstraction splits fstab lines by whitespace without honoring escaped whitespaces.

**Comment by igalic** [comment]
can you please post an example of this?

**Comment by gronke** [comment]
```
/foo\ bar/ /mnt nullfs ro 0 0
```

### Current Result
```
[0] /foo\
[1] bar/
[2] /mnt
[3] nullfs
[4] ro
[5] 0
```

### Expected Result
```
[0] /foo\ bar/
[1] /mnt
[2] nullfs
[3] ro
[4] 0
[5] 0
```

**Comment by igalic** [comment]
i think the correct solution would be here to use the underlying systems facilities to validate / parse fstab.

**Comment by gronke** [comment]
According to the [fstab man page](https://www.freebsd.org/cgi/man.cgi?query=fstab) it is https://www.freebsd.org/cgi/man.cgi?query=strunvis

> The first field, (fs_spec), describes the special device or remote  file system to be mounted. The contents are decoded by the strunvis(3) function. This allows using spaces or tabs in the device name which would be interpreted as field separators otherwise.

**Comment by nifoc** [comment]
Has this been fixed yet? Tried the following and it doesn't seem to work:

```
# iocage -v
Version	0.9.10 RC
# iocage fstab -a foobar "/mnt/dozer/Foo\ Bar /mnt/Foo\ Bar nullfs rw 0 0"
The destination's mountpoint exceeds 88 characters, this may cause failure!
Successfully added mount to foobar's fstab
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fstab.py", line 126, in cli
    add_path=add_path, header=header)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1055, in fstab
    exit_on_error=self.exit_on_error)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 65, in __init__
    self.__fstab_parse__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 75, in __fstab_parse__
    self.__fstab_mount__()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fstab.py", line 165, in __fstab_mount__
    raise RuntimeError(f"{stderr_data.decode('utf-8')}")
RuntimeError: mount_nullfs: /mnt/dozer/Foo\ Bar : No such file or directory
```

**Comment by gronke** [comment]
At the current time this is not supported yet. The issue is the fstab parser that splits each line on whitespace characters. To resolve this we need to replace escaped whitespaces with a placeholder first and then split the lines.
