### ISSUE TITLE
iocage_legacy jails cannot be started

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#128]
When attempting to start a legacy jail with long uuid, the name validation prevents to start it without modification.

```
root@freebsd:/usr/local/src/iocage_legacy # ./iocage activate zroot
root@freebsd:/usr/local/src/iocage_legacy # ./iocage list
  INFO: Creating zroot/iocage
  INFO: Creating zroot/iocage/jails
  INFO: Creating zroot/iocage/.defaults
  INFO: Creating zroot/iocage/download
  INFO: Creating zroot/iocage/releases
JID   UUID                                  BOOT  STATE  TAG                   IP
root@freebsd:/usr/local/src/iocage_legacy # ./iocage fetch
Supported releases are:
   10.3-RELEASE
    9.3-RELEASE
Please select a release [11.1-RELEASE]:   
base.txz                                      100% of   99 MB   34 MBps 00m03s
doc.txz                                       100% of 1395 kB 4471 kBps 00m00s
lib32.txz                                     100% of   17 MB   13 MBps 00m02s
src.txz                                       100% of  140 MB   41 MBps 00m03s
Extracting: base.txz
Extracting: doc.txz
Extracting: lib32.txz
Extracting: src.txz
* Updating base jail..
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching public key from update4.freebsd.org... done.
Fetching metadata signature for 11.1-RELEASE from update4.freebsd.org... done.
Fetching metadata index... done.
Fetching 2 metadata files... done.
Inspecting system... done.
Preparing to download files... done.
Fetching 6 patches.... done.
Applying patches... done.

The following files will be updated as part of updating to 11.1-RELEASE-p1:
/bin/freebsd-version
/usr/sbin/sshd
/usr/src/crypto/openssh/auth-passwd.c
/usr/src/sys/conf/newvers.sh
/usr/src/sys/kern/sys_socket.c
/usr/src/sys/netpfil/pf/pf.c
Installing updates... done.

Creating basejail ZFS datasets... please wait.
root@freebsd:/usr/local/src/iocage_legacy # ./iocage create -b tag=foo
root@freebsd:/usr/local/src/iocage_legacy # ioc list
+-----+--------------------------------------+---------+---------+----------+
| JID |                 NAME                 | RUNNING | RELEASE | IP4.ADDR |
+=====+======================================+=========+=========+==========+
| -   | bff1d3f7-a11a-11e7-acb3-001e67f56931 | no      | -       | -        |
+-----+--------------------------------------+---------+---------+----------+
root@freebsd:/usr/local/src/iocage_legacy # ioc start bff1d3f7-a11a-11e7-acb3-001e67f56931
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/src/libiocage/iocage/cli/start.py", line 61, in cli
    normal(jails, **start_args)
  File "/usr/local/src/libiocage/iocage/cli/start.py", line 89, in normal
    start_jails(jails, logger=logger, print_function=print_function)
  File "/usr/local/src/libiocage/iocage/cli/start.py", line 98, in start_jails
    print_function(jail.start())
  File "/usr/local/src/libiocage/iocage/cli/__init__.py", line 64, in print_events
    for event in generator:
  File "/usr/local/src/libiocage/iocage/lib/Jail.py", line 281, in start
    release = self.release
  File "/usr/local/src/libiocage/iocage/lib/Jail.py", line 1144, in __getattribute__
    return object.__getattribute__(self, key)
  File "/usr/local/src/libiocage/iocage/lib/Jail.py", line 1131, in release
    zfs=self.zfs
  File "/usr/local/src/libiocage/iocage/lib/Release.py", line 157, in __init__
    if not iocage.lib.helpers.validate_name(name):
  File "/usr/local/src/libiocage/iocage/lib/helpers.py", line 171, in validate_name
    return bool(_validate_name.fullmatch(name))
TypeError: expected string or bytes-like object
```

```
root@localhost:/usr/local/src/iocage_legacy # uname -a
FreeBSD localhost11.1-RELEASE-p1 FreeBSD 11.1-RELEASE-p1 #16 r313908+91baad1bb58(heads/remotes/origin/releng/11.1)-dirty: Mon Aug 28 12:06:18 UTC 2017     root@localhost:/usr/obj/usr/src/sys/VIMAGE  amd64
root@localhost:/usr/local/src/iocage_legacy # ./iocage --version
iocage 1.7.4 (2016/02/17)
```

**Comment by gronke** [comment]
fixed in #192
