### ISSUE TITLE
unsetting already unset config properties raises

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#135]
There is no user-set jail configuration property `allow_mount_zfs` available/

```
# cat /iocage/jails/padieu-samba/config.json 
{
    "basejail": "yes",
    "id": "myjail",
    "jail_zfs_dataset": "zroot/mydataset",
    "release": "11-STABLE"
}
```

### Current Result

- Unsetting the property raises an error

```
# ioc set jail_zfs=yes allow_mount_zfs jail_zfs_dataset=zroot/mydataset myjail
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/src/libiocage/iocage/cli/set.py", line 76, in cli
    updated_properties = set_properties(props, ioc_jail)
  File "/usr/local/src/libiocage/iocage/cli/set.py", line 112, in set_properties
    del target.config[key]
  File "/usr/local/src/libiocage/iocage/lib/Config/Jail/BaseConfig.py", line 440, in __delitem__
    del self.data[key]
KeyError: 'allow_mount_zfs'
```

### Expected Result

- Property is marked unchanged

**Comment by igalic** [comment]
*mumbles something about idempotency*

**Comment by gronke** [comment]
Turns out this bug is already fixed. 😀
