### ISSUE TITLE
renaming does not work after stopping a jail

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#139]
```
# ioc rename previous-name other-name
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/src/libiocage/iocage/cli/rename.py", line 44, in cli
    ioc_jail.rename(name)
  File "/usr/local/src/libiocage/iocage/lib/Jail.py", line 446, in rename
    dataset.rename(new_dataset_name)
  File "libzfs.pyx", line 2106, in libzfs.ZFSObject.rename (libzfs.c:47366)
libzfs.ZFSException: Device busy
```

### Steps to reproduce

1. Create Jail
2. Start Jail
3. Stop Jail
4. Rename Jail

(on HardenedBSD 11)

**Comment by gronke** [comment]
fixed in #187
