### ISSUE TITLE
temporary jails are not stopped when a release update fail

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#153]
When a release update fails, the jail created for it is not properly stopped, so that it would fail on the next attempt to update as well:

```
root@localhost/usr/local/src/libiocage # ioc fetch -r 11.0-RELEASE
[+] FetchRelease@11.0-RELEASE: OK [26.903s]: 4
  [+] ReleasePrepareStorage@11.0-RELEASE: OK [0.236s]: 1
  [+] ReleaseDownload@11.0-RELEASE: OK [4.106s]: 1
  [+] ReleaseExtraction@11.0-RELEASE: OK [22.561s]: 1
[+] ReleaseConfiguration@11.0-RELEASE: OK [0.003s]: 1
[+] ReleaseUpdateDownload@11.0-RELEASE: OK [0.431s]: 1
[-] RunReleaseUpdate@11.0-RELEASE: FAILED [0.532s]: 2
Jail 'None' is already running
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 113, in cli
    fetch_updates=fetch_updates
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 64, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Release.py", line 429, in fetch
    for event in ReleaseGenerator.update(self):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Release.py", line 616, in update
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Release.py", line 602, in update
    for event in self._update_freebsd_jail(jail):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Release.py", line 733, in _update_freebsd_jail
    for event in jail.start():
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 279, in start
    self.require_jail_stopped()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 989, in require_jail_stopped
    **kwargs
iocage.lib.errors.JailAlreadyRunning
```

Due to the fact, that the jail is internally called `None`, the error even occurs when updating another jail.

**Comment by gronke** [comment]
This is related to #28 - when rolling back on failure, this should both be resolved.

**Comment by igalic** [comment]
shouldn't this be fixed now?

**Comment by gronke** [comment]
@igalic yip, thanks
