### ISSUE TITLE
Error when creating a Basejail

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#218]
```
ioc create -b  -n arp-epair-test
Automatically fetching release '{resource.name}'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Jail/JailConfig.py", line 89, in __getitem__
    return super().__getitem__(key)
    File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Jail/BaseConfig.py", line 475, in __getitem__
    raise KeyError(f"Item not found: {key}")
KeyError: 'Item not found: id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 164, in cli
    new=True
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 256, in __init__
    logger=self.logger
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Jail/JailConfig.py", line 65, in __init__
    self["id"] = data[key]
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Jail/BaseConfig.py", line 498, in __setitem__
    setter_method(parsed_value, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Jail/BaseConfig.py", line 161, in _set_id
    if self["id"] == name:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Jail/JailConfig.py", line 92, in __getitem__
    return self.host.default_config[key]
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Host.py", line 121, in default_config
    return self.defaults.config
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Host.py", line 113, in defaults
    self._defaults.read_config()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 370, in read_config
    o = Resource.read_config(self)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 309, in read_config
    o = self.config_handler.read()  # type: typing.Dict[str, typing.Any]
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 314, in config_handler
    handler = object.__getattribute__(self, f"config_{self.config_type}")
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 228, in config_type
    self._config_type = self._detect_config_type()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 240, in _detect_config_type
    if self.config_json.exists:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Prototype.py", line 85, in exists
    return os.path.isfile(self.file)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Resource/ResourceConfig.py", line 51, in file
    self._file
  File "/usr/local/lib/python3.6/posixpath.py", line 78, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by gronke** [comment]
This issue was caused due to an `zroot/iocage` dataset without mountpoint. Child datasets did not get mounted as well.
