### ISSUE TITLE
ioc list -NH on empty list breaks: IndexError: list index out of range

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#220]
```
root@container-host1 ~# /usr/local/bin/ioc list 
+-----+------+---------+---------+----------+
| JID | NAME | RUNNING | RELEASE | IP4.ADDR |
+=====+======+=========+=========+==========+
+-----+------+---------+---------+----------+
root@container-host1 ~# /usr/local/bin/ioc list -NH
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 129, in cli
    _print_table(resources, columns, header, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 163, in _print_table
    table.add_rows(table_data)
  File "/usr/local/lib/python3.6/site-packages/texttable.py", line 358, in add_rows
    self.header(rows[0])
IndexError: list index out of range
root@container-host1 ~#
```

**Comment by gronke** [comment]
This issue seems to be fixed already. Although there is an error in the list output when using `-NH`: The first row is indented as header.
