### ISSUE TITLE
Unable to rename a jail

### ISSUE THREAD

**Issue by bwegrzyn** [iocage/libiocage#244]
After a fresh reboot on FreeNAS 11.1...

```bash
nas# iocage --version
Version	0.9.10 RC
```

```bash
nas# iocage stop plex
* Stopping plex
  + Running prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing jail process OK
  + Running poststop OK
nas# iocage list
+-----+------------+-------+--------------+------+
| JID |    NAME    | STATE |   RELEASE    | IP4  |
+=====+============+=======+==============+======+
| -   | plex       | down  | 11.1-RELEASE | DHCP |
+-----+------------+-------+--------------+------+
```

```bash
nas# iocage rename plex pms
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/rename.py", line 39, in cli
    ioc.IOCage(exit_on_error=True, jail=jail).rename(new_name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1232, in rename
    self.zfs.get_dataset(path).rename(new_path)
  File "libzfs.pyx", line 2126, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy
```

```bash
nas# zfs list | grep iocage
storage/iocage                                            3.31G  13.0T   100K  /mnt/iocage
storage/iocage/download                                    260M  13.0T    88K  /mnt/iocage/download
storage/iocage/download/11.1-RELEASE                       260M  13.0T   260M  /mnt/iocage/download/11.1-RELEASE
storage/iocage/images                                       88K  13.0T    88K  /mnt/iocage/images
storage/iocage/jails                                      2.12G  13.0T    88K  /mnt/iocage/jails
storage/iocage/jails/plex                                  968M  13.0T    96K  /mnt/iocage/jails/plex
storage/iocage/jails/plex/root                             968M  13.0T  1.87G  /mnt/iocage/jails/plex/root
storage/iocage/log                                          96K  13.0T    96K  /mnt/iocage/log
storage/iocage/releases                                    962M  13.0T    88K  /mnt/iocage/releases
storage/iocage/releases/11.1-RELEASE                       962M  13.0T    88K  /mnt/iocage/releases/11.1-RELEASE
storage/iocage/releases/11.1-RELEASE/root                  961M  13.0T   961M  /mnt/iocage/releases/11.1-RELEASE/root
storage/iocage/templates                                    88K  13.0T    88K  /mnt/iocage/templates
```

```bash
nas# cat /mnt/iocage/jails/plex/config.json 
{
    "CONFIG_VERSION": "9",
    "allow_chflags": "0",
    "allow_mount": "0",
    "allow_mount_devfs": "0",
    "allow_mount_nullfs": "0",
    "allow_mount_procfs": "0",
    "allow_mount_tmpfs": "0",
    "allow_mount_zfs": "0",
    "allow_quotas": "0",
    "allow_raw_sockets": "0",
    "allow_set_hostname": "1",
    "allow_socket_af": "0",
    "allow_sysvipc": "0",
    "available": "readonly",
    "basejail": "no",
    "boot": "off",
    "bpf": "yes",
    "children_max": "0",
    "cloned_release": "11.1-RELEASE",
    "comment": "none",
    "compression": "lz4",
    "compressratio": "readonly",
    "coredumpsize": "off",
    "count": "1",
    "cpuset": "off",
    "cputime": "off",
    "datasize": "off",
    "dedup": "off",
    "defaultrouter": "none",
    "defaultrouter6": "none",
    "depends": "none",
    "devfs_ruleset": "4",
    "dhcp": "on",
    "enforce_statfs": "2",
    "exec_clean": "1",
    "exec_fib": "0",
    "exec_jail_user": "root",
    "exec_poststart": "/usr/bin/true",
    "exec_poststop": "/usr/bin/true",
    "exec_prestart": "/usr/bin/true",
    "exec_prestop": "/usr/bin/true",
    "exec_start": "/bin/sh /etc/rc",
    "exec_stop": "/bin/sh /etc/rc.shutdown",
    "exec_system_jail_user": "0",
    "exec_system_user": "root",
    "exec_timeout": "60",
    "host_domainname": "none",
    "host_hostname": "plex",
    "host_hostuuid": "pms",
    "host_time": "yes",
    "hostid": "5ea4e75b-f509-11e7-b2ea-d05099c302d7",
    "interfaces": "vnet0:bridge0",
    "ip4": "new",
    "ip4_addr": "none",
    "ip4_saddrsel": "1",
    "ip6": "new",
    "ip6_addr": "none",
    "ip6_saddrsel": "1",
    "jail_zfs": "off",
    "jail_zfs_dataset": "",
    "jail_zfs_mountpoint": "",
    "last_started": "2018-01-14 05:33:48",
    "login_flags": "-f root",
    "mac_prefix": "02ff60",
    "maxproc": "off",
    "memorylocked": "off",
    "memoryuse": "off",
    "mount_devfs": "1",
    "mount_fdescfs": "1",
    "mount_linprocfs": "0",
    "mount_procfs": "0",
    "mountpoint": "readonly",
    "msgqqueued": "off",
    "msgqsize": "off",
    "nmsgq": "off",
    "notes": "none",
    "nsemop": "off",
    "nshm": "off",
    "nthr": "off",
    "openfiles": "off",
    "origin": "readonly",
    "owner": "root",
    "pcpu": "off",
    "priority": "99",
    "pseudoterminals": "off",
    "quota": "none",
    "release": "11.1-RELEASE-p6",
    "reservation": "none",
    "resolver": "/etc/resolv.conf",
    "rlimits": "off",
    "securelevel": "2",
    "shmsize": "off",
    "stacksize": "off",
    "stop_timeout": "30",
    "swapuse": "off",
    "sync_state": "none",
    "sync_target": "none",
    "sync_tgt_zpool": "none",
    "sysvmsg": "new",
    "sysvsem": "new",
    "sysvshm": "new",
    "template": "no",
    "type": "jail",
    "used": "readonly",
    "vmemoryuse": "off",
    "vnet": "on",
    "vnet0_mac": "02ff6014fa09,02ff6014fa0a",
    "vnet1_mac": "none",
    "vnet2_mac": "none",
    "vnet3_mac": "none",
    "wallclock": "off"
}
```

```bash
as# iocage list
+-----+------------+-------+--------------+------+
| JID |    NAME    | STATE |   RELEASE    | IP4  |
+=====+============+=======+==============+======+
| -   | pms        | down  | 11.1-RELEASE | DHCP |
+-----+------------+-------+--------------+------+
nas# iocage start pms
jail 'pms' not found!
nas# iocage start plex
* Starting plex
  + Started OK
  + Configuring VNET OK
  + Starting services OK
```

Expected the jail to get renamed. Looks like it failed halfway through as the `host_hostuuid` key in config.json was changed, but the location on the pool was not. I changed `host_hostuuid` back to plex and everything was fine.

I found #139 that was supposedly fixed, but I'm not sure if its included because Freenas 11.1 has iocage version 0.9.10 RC, but no releases are tagged on Github.

**Comment by bwegrzyn** [comment]
So I managed to solve this, but I'll leave this open as I suspect there might be a bug somewhere (especially since this occured after a clean reboot).

I was unable to rename or unmount the dataset using the `zfs` command too.

```bash
nas# zfs rename storage/iocage/jails/plex storage/iocage/jails/pms
cannot unmount '/mnt/iocage/jails/plex/root': Device busy
```

I couldn't find what was using the dataset, so I forcefully unmounted it which was successful.

```bash
nas# zfs unmount -f /mnt/iocage/jails/plex/
```

At this point I was able to rename my jail fine, but it failed to start because the fstab file was pointing to the wrong mounting location.

```bash
nas# iocage rename plex pms
Jail: plex renamed to pms
nas# iocage start pms
* Starting pms
  + Start FAILED
mount: /mnt/iocage/jails/plex: No such file or directory
jail: /sbin/mount -t nullfs -o rw /mnt/storage/media /mnt/iocage/jails/plex/root/mnt/media: failed
```

I edited the `/mnt/iocage/jails/pms/fstab` file with the updated mount location, and everything seems to be ok now.

**Comment by gronke** [comment]
@bwegrzyn I believe your issue refers to https://github.com/iocage/iocage. Would you mind re-opening it over there in case it still persists?
