### ISSUE TITLE
 module 'ucl' has no attribute 'dump'

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#283]
I was trying a new **clone** feature but it gets stuck on `ucl` command.

```
+] JailClone@d8cf14ee: OK [1.288s]: 1
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/clone.py", line 76, in cli
    print_function(ioc_destination_jail.clone_from_jail(ioc_source_jail))
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 71, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 849, in clone_from_jail
    self.save()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 938, in save
    self._write_config(self.config.data)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 325, in _write_config
    self.config_handler.write(data)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Prototype.py", line 87, in write
    text_data = str(self.map_output(data))
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Config/Type/UCL.py", line 48, in map_output
    return str(iocage.lib.helpers.to_ucl(data))
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/helpers.py", line 322, in to_ucl
    return str(ucl.dump(output_data))
AttributeError: module 'ucl' has no attribute 'dump'
```

I tried a few things but before I was even able to run `ioc list` I needed to install py-ucl via pkg manually which is kinda weird as I saw there was some build issues around that a few days ago. 

I'm using **daeebedba180d19da7230da0f4bb99afb2a7def2** commit from master and I try to run `ioc clone d8cf14ee-2c22-11e8-8d77-7071bca7c826 testclone`

**Comment by gronke** [comment]
First there were issues installing ucl via pip, but the I had to revert using the pkg `py36-ucl` in #278 because it lacked the dump method. You can uninstall the FreeBSD and pip package and re-install.

```
pkg remove py36-ucl
python3.6 -m pip uninstall ucl
make install
```

**Comment by urosgruber** [comment]
If I do this. I get 

```
root@gandalf:/root/libiocage # ioc list
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 7, in <module>
    from iocage.cli import cli
  File "/usr/local/lib/python3.6/site-packages/iocage/__init__.py", line 24, in <module>
    from iocage.lib import errors, events  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/errors.py", line 29, in <module>
    import iocage.lib.events  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/events.py", line 31, in <module>
    import iocage.lib.Jail  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 33, in <module>
    import iocage.lib.helpers
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/helpers.py", line 30, in <module>
    import ucl
ModuleNotFoundError: No module named 'ucl'
```

After executing `ioc list`.
But **/usr/local/lib/python3.6/site-packages/ucl-0.8-py3.6.egg-info/** is there.

**Comment by gronke** [comment]
That's strange. Make should have installed it from the requirements.txt (where it should be pinned to 0.8.0). You could try and do it manually:

```
python3.6 -m pip install -Iv ucl==0.8.0
```

**Comment by urosgruber** [comment]
Hm that worked. What I also did was to remove pip cache and I need to try a few times but I works now even through `make install`. So maybe It has something to do with pip cache. I'll close this for now and If I encounter this again during testing I'll reopen. Thanks for suggestions,

**Comment by gronke** [comment]
Will add the `-I` option to the Makefile.
