### ISSUE TITLE
Multi-Pool dataset mountpoint not found

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#293]
This issue was reported by @urosgruber in https://github.com/iocage/libiocage/pull/287#issuecomment-378733053

```
[-] FetchRelease@boxr/11.1-RELEASE: ...
  [-] ReleasePrepareStorage@boxr/11.1-RELEASE: ...
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 138, in cli
    fetch_updates=fetch_updates
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 71, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Release.py", line 507, in fetch
    self.create_resource()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 290, in create_resource
    os.chmod(self.dataset.mountpoint, 0o700)
TypeError: chmod: path should be string, bytes, os.PathLike or integer, not NoneType
```

The datasets existing after the operation were:

```
sys/boxr                                              320K  1.47T    88K  none
sys/boxrjails                                         88K  1.47T    88K  none
sys/boxrreleases                                     144K  1.47T  55.5K  none
sys/boxrreleases/11.1-RELEASE                         88K  1.47T    88K  none
```

**Comment by gronke** [comment]
It is interesting that the `sys/boxrjails` and `sys/boxrreleases` datasets exist. They should have been `sys/boxr/jails` and `sys/boxr/releases` instead.

I was not able to reproduce this issue with neither of this steps:

```
zfs create zroot/urosgruber
zfs mountpoint=/urosgruber zroot/urosgruber
sysrc ioc_dataset_boxr="zroot/urosgruber"
ioc fetch -r 11.1-RELEASE
```

or alternatively without the existing dataset:

```
zfs destroy -r zroot/urosgruber
sysrc ioc_dataset_boxr="zroot/urosgruber"
ioc fetch -r 11.1-RELEASE
```

@urosgruber can you please paste the output of `sysrc -a | grep ioc_dataset`?

**Comment by urosgruber** [comment]
@gronke just noticed `/` was lost from my description

```
sys/boxr
sys/boxr/jails
sys/boxr/releases
sys/boxr/releases/11.1-RELEASE
```

is the correct one

**Comment by urosgruber** [comment]
Also tested the second procedure without existing data set and the error is I think the same

```
[-] FetchRelease@boxr/11.1-RELEASE: ...
  [-] ReleasePrepareStorage@boxr/11.1-RELEASE: ...
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 138, in cli
    fetch_updates=fetch_updates
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 71, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Release.py", line 507, in fetch
    self.create_resource()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Resource.py", line 290, in create_resource
    os.chmod(self.dataset.mountpoint, 0o700)
TypeError: chmod: path should be string, bytes, os.PathLike or integer, not NoneType
```
And `zfs list | grep box` after 
```
sys/boxr                                                     166K  1.46T  55.5K  none
sys/boxr/releases                                            111K  1.46T  55.5K  none
sys/boxr/releases/11.1-RELEASE                              55.5K  1.46T  55.5K  none
```

I'm using **c257f4dde0f45dcad821a4d58776dbffc91864c7** commit

**Comment by urosgruber** [comment]
@gronke I think I found what the root cause is. I didn't have mountpoint set on my **sys** pool which leads to not heaving it also on **sys/boxr** After I set it up `fetch` command worked. Maybe it would be nice to have some better message in this case?
