### ISSUE TITLE
FreeBSD 10.x does not utilize libxo on jls

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#298]
When running `ioc list` I'm getting 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/JailState.py", line 122, in query
    ], shell=False, stderr=subprocess.DEVNULL)  # nosec TODO use helper
  File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/sbin/jls', '-v', '--libxo=json']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 145, in cli
    _print_table(resources, columns, header, _sort)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/list.py", line 160, in _print_table
    for resource in resources:
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jails.py", line 101, in __iter__
    self.states.query()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/JailState.py", line 129, in query
    raise iocage.lib.errors.JailStateUpdateFailed()
iocage.lib.errors.JailStateUpdateFailed: Updating the jail state with jls failed
```

FreeBSD version 10.x (tested on 10.3 but event 10.4 does not show `--libxo` flag in **man**)

**Comment by gronke** [comment]
Indeed, `jls` does not come with libxo support on FreeBSD 10.4.

- [man jls from FreeBSD 10.4-RELEASE](https://www.freebsd.org/cgi/man.cgi?query=jls&apropos=0&sektion=8&manpath=FreeBSD+10.4-RELEASE&arch=default&format=html)
- [man jls from FreeBSD 11.1-RELEASE](https://www.freebsd.org/cgi/man.cgi?query=jls&apropos=0&sektion=8&manpath=FreeBSD+11.1-RELEASE&arch=default&format=html)
