### ISSUE TITLE
pip.req is deprecated in pip 10

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#307]
```
$ make install
which pkg && pkg install -q -y libucl py36-cython rsync python36 py36-libzfs py36-sysctl || true
/usr/sbin/pkg
The most recent version of packages are already installed
python3.6 -m ensurepip
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages
python3.6 -m pip install -Ur requirements.txt
Requirement already up-to-date: click==6.7 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (6.7)
Requirement already up-to-date: texttable==0.9.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.9.0)
Requirement already up-to-date: tqdm==4.17.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 3)) (4.17.1)
Requirement already up-to-date: ucl==0.8.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4)) (0.8)
python3.6 -m pip install -U .
Processing /usr/local/src/libiocage
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-vlhyb6cm/setup.py", line 28, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-vlhyb6cm/
*** Error code 1

Stop.
make: stopped in /usr/local/src/libiocage
make install  5.17s user 4.04s system 96% cpu 9.503 total
```

**Comment by gronke** [comment]
```python3
try:
    from pip._internal.req import parse_requirements
except ModuleNotFoundError:
    from pip.req import parse_requirements
```

**Comment by kamikaze** [comment]
ImportError
