### ISSUE TITLE
Better error message when setting invalid interfaces

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#353]
```
# python3.6 . set interfaces="invalid" foobar
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 48, in <module>
    main()
  File "./__main__.py", line 42, in main
    cli(prog_name="iocage")
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./iocage/cli/set.py", line 76, in cli
    updated_properties = _set_properties(props, ioc_jail)
  File "./iocage/cli/set.py", line 106, in _set_properties
    changed = target.config.set(key, value)
  File "./iocage/lib/Config/Jail/BaseConfig.py", line 603, in set
    self.__setitem__(key, value, **kwargs)
  File "./iocage/lib/Config/Jail/BaseConfig.py", line 560, in __setitem__
    special_property.set(value)
  File "./iocage/lib/Config/Jail/Properties/Interfaces.py", line 68, in set
    jail_if, bridge_if = nic_pair.split(":", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by igalic** [comment]
there's a lot to unpack here.
