### ISSUE TITLE
ioc destroy --force --release X does not work

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#363]
Currently our automation help of skipping the prompt (`--force`) does not work when deleting releases:

```
root@container-host1 ~# /usr/local/bin/ioc destroy --force --release 10.4-RELEASE
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/destroy.py", line 110, in cli
    if (force and item.running) is True:
AttributeError: 'ReleaseGenerator' object has no attribute 'running'
root@container-host1 ~# 
```

**Comment by igalic** [comment]
i have a patch for this

```diff
diff --git a/iocage/cli/destroy.py b/iocage/cli/destroy.py
index f2071d3..6799c23 100644
--- a/iocage/cli/destroy.py
+++ b/iocage/cli/destroy.py
@@ -107,7 +107,7 @@ def cli(
 
         old_mountpoint = item.dataset.mountpoint
 
-        if (force and item.running) is True:
+        if (not release and force and item.running) is True:
             ctx.parent.print_events(item.stop(force=True))
             item.state.query()
 ```
