### ISSUE TITLE
ioc create: stack traces on invalid input

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#415]
```python-traceback
# ioc create test
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/create.py", line 114, in cli
    resource_selector = iocage.lib.ResourceSelector.ResourceSelector(name)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ResourceSelector.py", line 40, in __init__
    self.name = name
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ResourceSelector.py", line 49, in name
    name_components = value.split("/", maxsplit=1)
AttributeError: 'NoneType' object has no attribute 'split'
```

Proper warnings/errors should be printed instead.

**Comment by gronke** [comment]
With #423 the `-n` option was deprecated, so that this issue can no longer occur.
