### ISSUE TITLE
Traceback when updating all jails ("*")

### ISSUE THREAD

**Issue by yonk42** [iocage/libiocage#451]
I ran into this traceback when trying to update all jails.

```
[root@host ~]# ioc update "*"
[-] RunReleaseUpdate@11.1-RELEASE: FAILED [4.556s]: 9
  [-] ExecuteReleaseUpdate@11.1-RELEASE: FAILED [4.311s]: 8
    [-] JailForkExec@postfix_u: FAILED [3.831s]: 6
      [+] JailLaunch@postfix_u: OK [0.982s]: 1
      [+] JailServicesStart@postfix_u: OK [0.479s]: 1
      [-] JailExec@postfix_u: FAILED [2.356s]: 3
        [+] JailDestroy@postfix_u: OK [0.464s]: 1
        [+] JailMountTeardown@postfix_u: OK [0.947s]: 1
```
```python-traceback
Release update of '11.1-RELEASE' failed: freebsd-update failed
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/update.py", line 76, in cli
    changed = print_function(jail.updater.apply())
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 93, in print_events
    if event.message is not None:
AttributeError: 'RunReleaseUpdate' object has no attribute 'message'
```

This only seems to happen when "*" is used, if I specify the postfix jail directly no traceback is generated:
```
[root@host ~]# ioc update postfix
[-] RunReleaseUpdate@11.1-RELEASE: FAILED [4.556s]: 9
  [-] ExecuteReleaseUpdate@11.1-RELEASE: FAILED [4.311s]: 8
    [-] JailForkExec@postfix_u: FAILED [3.831s]: 6
      [+] JailLaunch@postfix_u: OK [0.982s]: 1
      [+] JailServicesStart@postfix_u: OK [0.479s]: 1
      [-] JailExec@postfix_u: FAILED [2.356s]: 3
        [+] JailDestroy@postfix_u: OK [0.464s]: 1
        [+] JailMountTeardown@postfix_u: OK [0.947s]: 1
Release update of '11.1-RELEASE' failed: freebsd-update failed
```

My libiocage version: `ioc, version 0.2.12 09/17/2017` (built from source from master)

**Comment by gronke** [comment]
It seems you were using an outdated revision (the RunReleaseUpdate was renamed a while ago).

Cannot reproduce. Please reopen in case the error still occurs.
