### ISSUE TITLE
Migrate feature tracebacks

### ISSUE THREAD

**Issue by AwUnic** [iocage/libiocage#477]
```
nas% sudo ioc migrate "*"     
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/migrate.py", line 79, in cli
    host=host
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 83, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/migrate.py", line 92, in _migrate_jails
    event = JailMigrationEvent(jail=jail)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/migrate.py", line 47, in __init__
    iocage.lib.events.IocageEvent.__init__(self, jail=jail)
TypeError: __init__() got an unexpected keyword argument 'jail'

```
When trying to migrate jails from iocage-legacy zfs basejails to libiocage basejails this error occures

**Comment by AwUnic** [comment]
````
nas% sudo ioc migrate "*"
[-] JailMigrationEvent@abc5da5b-a5f9-11e6-b689-408d5cc0a346: ...
  [+] JailClone@abc5da5b-a5f9-11e6-b689-408d5cc0a346: OK [0.325s]: 1
  [+] JailFstabUpdate@abc5da5b-a5f9-11e6-b689-408d5cc0a346: OK [0.067s]: 1
  [-] ZFSDatasetDestroy@zroot/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346: ...
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/migrate.py", line 79, in cli
    host=host
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/__init__.py", line 83, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/migrate.py", line 143, in _migrate_jails
    yield from jail.destroy(event_scope=event.scope)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 975, in destroy
    raise e
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/Jail.py", line 972, in destroy
    self.zfs.delete_dataset_recursive(self.dataset)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ZFS.py", line 97, in delete_dataset_recursive
    self.delete_dataset_recursive(child)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ZFS.py", line 102, in delete_dataset_recursive
    dataset.umount()
  File "libzfs.pyx", line 2361, in libzfs.ZFSDataset.umount
libzfs.ZFSException: Device busy

```

**Comment by gronke** [comment]
@AwUnic can you please list of the jails mounts?

```
mount | grep abc5da5b-a5f9-11e6-b689-408d5cc0a346
```

**Comment by AwUnic** [comment]
The jails have been stopped with iocage legacy. One of them is now in dire state and will not start with iocage legacy anymore.
The cloned jail in libiocage also doesn"t start, however the folder structure seems to be intact.
`nas% sudo ioc -d spam start usenet
/etc/rc.conf was read from /etc/rc.conf
Updated /etc/rc.conf data from /etc/rc.conf
Found active ZFS pool zroot
Querying all running jails status
/etc/rc.conf was read from /iocage/jails/usenet/root/etc/rc.conf
Updated /etc/rc.conf data from /iocage/jails/usenet/root/etc/rc.conf
Configuring nameserver for Jail 'usenet'
[+] JailResolverConfig: SKIPPED [0.001s]: 2
resolv.conf untouched
Resource limits disabled
[-] JailLaunch@usenet: ...
/etc/rc.conf was not modified - skipping write
Setting fstab auto-creation placeholder
Adding line to fstab: /data/movies	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/movies	nullfs	rw	0	0
Adding line to fstab: /data/tv	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/tv	nullfs	rw	0	0
[-] JailLaunch@usenet: FAILED [0.786s]: 25
fstab loaded from /iocage/jails/usenet/fstab
Setting fstab auto-creation placeholder
Adding line to fstab: /data/movies	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/movies	nullfs	rw	0	0
Adding line to fstab: /data/tv	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/tv	nullfs	rw	0	0
Adding line to fstab: /data/books	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/books	nullfs	rw	0	0
fstab loaded from /iocage/jails/usenet/fstab
/iocage/jails/usenet/fstab written
Reading devfs.rules from /etc/devfs.rules
Executing (interactive): /usr/sbin/jail -c ip4.addr=re0|10.0.0.101/24 ip4.saddrsel=1 ip4=new ip6.addr= ip6.saddrsel=1 ip6=new name=ioc-usenet host.hostname=abc5da5b-a5f9-11e6-b689-408d5cc0a346 host.domainname=local path=/iocage/jails/usenet/root securelevel=2 host.hostuuid=usenet devfs_ruleset=4 enforce_statfs=2 children.max=0 allow.set_hostname=0 allow.sysvipc=0 exec.prestart="/iocage/jails/usenet/launch-scripts/prestart.sh" exec.prestop="/iocage/jails/usenet/launch-scripts/prestop.sh" exec.poststop="/iocage/jails/usenet/launch-scripts/poststop.sh" exec.jail_user=root sysvmsg=new sysvsem=new sysvshm=new allow.raw_sockets=0 allow.chflags=0 allow.mount=0 allow.mount.devfs=0 allow.mount.nullfs=0 allow.mount.procfs=0 allow.mount.fdescfs=0 allow.mount.zfs=0 allow.quotas=0 allow.socket_af=0 exec.timeout=60 stop.timeout=30 mount.fstab=/iocage/jails/usenet/fstab mount.devfs=1 mount.fdescfs=1 allow.mount.tmpfs=0 allow.dying persist exec.poststart="/iocage/jails/usenet/launch-scripts/poststart.sh"
  jail: mount.fstab: /iocage/jails/usenet/root/iocage: No such file or directory
Jail 'usenet' was not started
Launching jail usenet failed
Writing jail.conf file to /iocage/jails/usenet/launch-scripts/jail.conf
Executing (interactive): /usr/sbin/jail -v -r -f /iocage/jails/usenet/launch-scripts/jail.conf ioc-usenet
  jail: "ioc-usenet" not found
Destroying jail usenet failed
Manually executing prestop and poststop hooks
Executing: /iocage/jails/usenet/launch-scripts/prestop.sh

Executing: /iocage/jails/usenet/launch-scripts/poststop.sh
`

**Comment by gronke** [comment]
This fstab lines seem to be wrong:

```
/data/movies	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/movies	nullfs	rw	0	0
/data/tv	/iocage/jails/usenet/root/iocage/jails/abc5da5b-a5f9-11e6-b689-408d5cc0a346/root/mnt/tv	nullfs	rw	0	0
```

Obviously the renaming of the mount source did not succeed. In consequeuce of that the jail does not start because there is no `/iocage` directory in the jails root dataset:

```
jail: mount.fstab: /iocage/jails/usenet/root/iocage: No such file or directory
```

**Comment by foo2342** [comment]
We noticed them as well, updated them and now the jail starts :)

**Comment by foo2342** [comment]
All jails with mounts needed manual intervention to adjust the paths, and I needed to clean up some datasets from the failed jail migration.
