### ISSUE TITLE
exception when any zpool on a system is unavailable

### ISSUE THREAD

**Issue by TypedLambda** [iocage/libiocage#520]
the root pool is zroot an is available. a second pool was imported, but no drive available to the system
(pool not present, but still imported / known to the system)

Activating the present pool is not possible (exception)
this should probably be handled (ignore pool).

ioc, version 0.3.0 2018/08/25
```
# ioc activate zroot
```

```python-traceback
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 10, in <module>
    sys.dd:exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ioc/activate.py", line 62, in cli
    logger=logger
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 187, in __init__
    self._configure_from_pool_property()
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 205, in _configure_from_pool_property
    active_pool = self._active_pool_or_none
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 300, in _active_pool_or_none
    if self.is_pool_active(pool):
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 389, in is_pool_active
    return self._is_pool_active(pool)
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 396, in _is_pool_active
    self.ZFS_POOL_ACTIVE_PROPERTY
  File "/usr/local/lib/python3.6/site-packages/iocage/Datasets.py", line 405, in _get_pool_property
    if prop in pool.root_dataset.properties:
  File "libzfs.pyx", line 1613, in libzfs.ZFSPool.root_dataset.__get__
libzfs.ZFSException: dataset does not exist
```

**Comment by gronke** [comment]
libiocage expects all pools to be available to be operational. I recommend you to disable it from the rc.conf file for the time it is unavailable.

@TypedLambda can you please share the iocage related content of your `/etc/rc.conf` file? Activation of pools it not necessary when the datasets are selected via the rc.conf method.

This is a bug in iocage anyway because I'd expect a proper error message instead of a stack trace in any way.

This issue is flagged as docs as well because the handbook should be updated accordingly.

**Comment by TypedLambda** [comment]
I don’t have any settings in rc.,
I just entered the activation command,
This is a new installation.

**Comment by gronke** [comment]
Ah, I see. So you have two pools on your host, but only one is available. Because libiocage attempts to read from them both, it fails checking whether iocage is active there or not. Is this correct?

**Comment by TypedLambda** [comment]
Probably. I wasn’t even aware of the second pool. It was  from a usb disk previously connected.

**Comment by gronke** [comment]
#521 should help. Could you check if the `fix/deal-with-unavailable-pools` branch resolves your issue?

**Comment by igalic** [comment]
@TypedLambda #521 has now been merged, so no need to fiddle around with branches to test, just pull the latest master!

i'll close this issue for now, as we believe that this should fix your issue.

**Comment by TypedLambda** [comment]
Thanks, sorry I couldn’t test it. I’m on A short Holliday without my pc.
