### ISSUE TITLE
ioc create is broken

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#71]
Using latest master `ioc create` creates jail half way with and error
```
9f24cf51 could not be created!
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 12, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/libiocage/cli/create.py", line 156, in cli
    jail.create(release.name)
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/Jail.py", line 402, in create
    self.config.save()
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/JailConfig.py", line 209, in save
    self.jail.rc_conf.save()
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/Jail.py", line 162, in rc_conf
    logger=self.logger
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/RCConf.py", line 41, in __init__
    self.path = path
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/RCConf.py", line 52, in path
    self._read_file()
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/RCConf.py", line 63, in _read_file
    new_keys = set(data.keys())
UnboundLocalError: local variable 'data' referenced before assignment
```
But `ioc list` show newly created jail 
```
+-----+------------+--------------------------------------+---------+--------------+----------------+-----------+--------+
| JID |    TAG     |                 NAME                 | RUNNING |   RELEASE    |    IP4.ADDR    |   TYPE    | LEGACY |
+=====+============+======================================+=========+==============+================+===========+========+
| -   | -          | 9f24cf51-9ae4-4f28-88f8-a71dabadcf39 | no      | 11.1-RELEASE | -              | -         | no     |
+-----+------------+--------------------------------------+---------+--------------+----------------+-----------+--------+
```
And then `ioc get all 9f24cf51-9ae4-4f28-88f8-a71dabadcf39` throws exception as well
```
basejail:no
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 12, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/libiocage/cli/get.py", line 95, in cli
    value = jail.config.get_string(key)
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/JailConfig.py", line 504, in get_string
    return self.stringify(self.__getitem__(key))
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/JailConfig.py", line 546, in __getitem__
    return self.defaults[key]
KeyError: 'clonejail'
```
And funny thing, jail can be started with `ioc start 9f24cf51-9ae4-4f28-88f8-a71dabadcf39` 

Note: activate was done by iocage legacy.

**Comment by gronke** [comment]
Fixed in previous commits
