### ISSUE TITLE
Release updates of 10.3-RELEASE failed

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#84]
```
root@zwei:/usr/local/src/libiocage # ioc fetch -r 10.3-RELEASE
[+] FetchRelease: OK [21.26s]: 4
  [+] ReleasePrepareStorage: OK [0.201s]: 1
  [+] ReleaseDownload: OK [3.355s]: 1
  [+] ReleaseExtraction: OK [17.703s]: 1
[+] ReleaseConfiguration: OK [0.002s]: 1
[-] ReleaseUpdateDownload: ...
Command exited with 1: /zroot/iocage/releases/10.3-RELEASE/updates/freebsd-update.sh -d /zroot/iocage/releases/10.3-RELEASE/updates -f /zroot/iocage/releases/10.3-RELEASE/updates/freebsd-update.conf --not-running-from-cron fetch
Command exited with 1
Traceback (most recent call last):
  File "/usr/local/bin/ioc", line 12, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/libiocage/cli/fetch.py", line 98, in cli
    fetch_updates=fetch_updates
  File "/usr/local/lib/python3.6/site-packages/libiocage/cli/__init__.py", line 64, in print_events
    for event in generator:
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/Release.py", line 393, in fetch
    for event in ReleaseGenerator.fetch_updates(self):
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/Release.py", line 526, in fetch_updates
    ], logger=self.logger)
  File "/usr/local/lib/python3.6/site-packages/libiocage/lib/helpers.py", line 139, in exec
    logger=logger
libiocage.lib.errors.CommandFailure: Command exited with 1
```

**Comment by gronke** [comment]
```
# /iocage/releases/10.3-RELEASE/updates/freebsd-update.sh -d /iocage/releases/10.3-RELEASE/updates -f /iocage/releases/10.3-RELEASE/updates/freebsd-update.conf --not-running-from-cron fetch
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.1-RELEASE from update6.freebsd.org... done.
Fetching metadata index... done.

The update metadata is correctly signed, but
failed an integrity check.
Cowardly refusing to proceed any further.

# echo $?                                                                                                               1
1
```

**Comment by skarekrow** [comment]
You need to set the RELEASE via the `UNAME_R` environment variable, as its trying to update 10.3 with 11.1.

**Comment by gronke** [comment]
@skarekrow thanks, you're right. I forgot to set the `-r` flag on `freebsd-update.sh`: https://github.com/freebsd/freebsd/blob/master/usr.sbin/freebsd-update/freebsd-update.sh#L48
